apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: input-images
  namespace: kafka
  labels:
    strimzi.io/cluster: my-kafka
spec:
  topicName: "input/images"
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
