apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: processed-frames
  namespace: kafka
  labels:
    strimzi.io/cluster: my-kafka
spec:
  topicName: "processed/frames"
  partitions: 3
  replicas: 3
  config:
    retention.ms: 259200000
    cleanup.policy: delete
